### ISSUE TITLE
popup-blocker adversely affecting Youtube

### ISSUE THREAD

**Issue by kruleworld** [schomery/popup-blocker#54] opened 2017-09-02 12:16 UTC
starting today, the plugin stops youtube main page from loading. Only displays the top frame and nothing else. as soon as turn off this plugin, it works ok and fails when turned back on.

**Comment by schomery** [comment] 2017-09-02 12:43
Duplicate of https://github.com/schomery/popup-blocker/issues/53?

**Closed** 2018-08-13 14:10 UTC
