### ISSUE TITLE
No user intervention

### ISSUE THREAD

**Issue by JeremyWW** [schomery/popup-blocker#13] opened 2017-01-15 00:23 UTC
Seems very effective but there's no menu or dialogue offering the user any choices for popup handling. From the description I thought it was supposed to offer user choice. I'm waiting for the first site where it blocks something it shouldn't.

**Comment by narcolepticinsomniac** [comment] 2017-01-15 03:47
Right-click the icon and select "options". I agree there should be a popup, but there are quite a few cool options for popup handling. The dev version has even more already. I expect the UI will get some improvements soon as well.

**Comment by JeremyWW** [comment] 2017-01-15 12:23
I'm sorry. My post was not clear at all. I'm using this in FX for Android, where no options are available anywhere.

**Comment by schomery** [comment] 2017-01-16 09:48
Popup Blocker is based on WebExtension platform. This platform is very limited. Basically there is no access to low level APIs at all. Hence there is no way to fix the options UI issue on Firefox for Android. Since I got too many negative reviews, I removed support for Firefox for Android until the issue is fixed by Mozilla. Sorry there is nothing we can do here.

**Closed by schomery** 2017-01-16 09:48 UTC
